/**
 * El editor, en español — sin librería de i18n y sin big-bang.
 *
 * ## Por qué la CLAVE es la frase en inglés
 *
 * Parece pobre al lado de un `editor.media.import`, y es justo al revés. Este repositorio es un
 * FORK: lo que se traduce hoy se va a encontrar mañana con un `git merge upstream/main` que cambia
 * componentes enteros. Con claves inventadas, cada cambio de upstream deja una clave huérfana que
 * no rompe nada y **se queda en inglés en silencio** — el peor resultado, porque nadie lo nota.
 *
 * Con la frase inglesa como clave pasan tres cosas que valen más que la elegancia:
 *
 * 1. **Lo no traducido se ve, y funciona.** `t("Add track")` sin entrada devuelve `"Add track"`:
 *    la pantalla queda en inglés en ese punto, no vacía ni rota.
 * 2. **Traducir es incremental.** Se pueden añadir cien frases hoy y cien mañana sin tocar código.
 * 3. **El rebase no miente.** Si upstream cambia «Add track» por otra cosa, la traducción deja de
 *    aplicar y se ve en pantalla, en vez de aplicarse a un texto que ya no existe.
 *
 * ## Por qué no i18next
 *
 * Aquí hay UN idioma de destino y ~4.000 cadenas repartidas en 287 componentes. Una librería añade
 * proveedor, carga asíncrona, plurales y un formato de archivo — infraestructura para un problema
 * que no tenemos. Si algún día el editor se vende en dos idiomas, esta función se sustituye por la
 * librería y las claves ya están puestas: son las frases originales, que es lo que cualquier
 * extractor de i18n habría generado igual.
 *
 * ## Alcance, dicho sin adornos
 *
 * Está traducida la CÁSCARA del editor —lo que se toca al montar— no las 287 pantallas. Lo que
 * falte sale en inglés y se puede ir sumando aquí sin tocar un solo componente.
 */

/**
 * Diccionario. La clave es el texto original, tal cual aparece en el componente.
 *
 * Tuteo rolo, nunca voseo: es la voz de la casa y aplica igual acá que en SkyNet.
 */
const ES: Readonly<Record<string, string>> = {
  // ── Barra superior y navegación ───────────────────────────────────────────
  "Video Editor": "Editor de video",
  "Motion Design": "Diseño en movimiento",
  Export: "Exportar",
  "Back to home": "Volver al inicio",
  "Action history": "Historial de acciones",
  "Audio mixer": "Mezclador de audio",
  Undo: "Deshacer",
  Redo: "Rehacer",
  Save: "Guardar",
  Saving: "Guardando",
  Saved: "Guardado",
  Settings: "Ajustes",

  // ── Riel de paneles ───────────────────────────────────────────────────────
  Media: "Material",
  Text: "Texto",
  Graphics: "Gráficos",
  Effects: "Efectos",
  Transitions: "Transiciones",
  Audio: "Audio",
  Captions: "Subtítulos",
  Templates: "Plantillas",

  // ── Panel de material ─────────────────────────────────────────────────────
  Import: "Importar",
  "Import Media": "Importar material",
  "Add media": "Añadir material",
  "Add to timeline": "Añadir a la línea de tiempo",
  Record: "Grabar",
  "No media imported": "Todavía no hay material",
  "Drag files here or click to import": "Arrastra archivos acá o haz clic para importar",
  "Asset not found": "No encuentro ese archivo",

  // ── Línea de tiempo ───────────────────────────────────────────────────────
  "Add track": "Añadir pista",
  "Add Track": "Añadir pista",
  Track: "Pista",
  Split: "Partir",
  Delete: "Borrar",
  Duplicate: "Duplicar",
  Copy: "Copiar",
  Paste: "Pegar",
  Cut: "Cortar",
  Lock: "Bloquear",
  Unlock: "Desbloquear",
  Mute: "Silenciar",
  Unmute: "Quitar silencio",
  Hide: "Ocultar",
  Show: "Mostrar",
  Solo: "Solo",
  "Zoom in": "Acercar",
  "Zoom out": "Alejar",
  "Fit to window": "Ajustar a la ventana",

  // ── Reproductor e inspector ───────────────────────────────────────────────
  Player: "Reproductor",
  Play: "Reproducir",
  Pause: "Pausar",
  "No selection": "Nada seleccionado",
  "Select a clip to view its properties": "Elige un clip para ver sus propiedades",
  Properties: "Propiedades",
  Transform: "Transformación",
  Position: "Posición",
  Scale: "Escala",
  Rotation: "Rotación",
  Opacity: "Opacidad",
  Volume: "Volumen",
  Speed: "Velocidad",
  Duration: "Duración",

  // ── Texto y títulos ───────────────────────────────────────────────────────
  "Add Title": "Añadir título",
  "Caption text here": "Escribe el subtítulo acá",
  Caption: "Subtítulo",
  "Add title presets and caption elements.": "Títulos listos y subtítulos.",
  "Create shapes, arrows, and SVG overlays.": "Formas, flechas y superposiciones SVG.",

  // ── Exportación ───────────────────────────────────────────────────────────
  Exporting: "Exportando",
  "Export Video": "Exportar video",
  Quality: "Calidad",
  Format: "Formato",
  Resolution: "Resolución",
  Cancel: "Cancelar",
  Close: "Cerrar",
  Done: "Listo",

  "AI Generate": "Generar con IA",
  Recipes: "Recetas",
  "Project Templates": "Plantillas de proyecto",
  "Project Media": "Material del proyecto",
  // ── Errores y estados ─────────────────────────────────────────────────────
  Loading: "Cargando",
  "Loading editor...": "Abriendo el editor…",
  Error: "Error",
  "Try again": "Intentar de nuevo",
  // ── Editor completo (extraído de los componentes, 15-ago) ──────────────────
  "A/B Preview": "Comparar A/B",
  "AI Aggregator": "Agregador de IA",
  "AI Aggregator provider": "Proveedor agregador",
  "AI Assistant (LLM)": "Asistente (modelo de lenguaje)",
  "AI Assistant provider": "Proveedor del asistente",
  "AI Auto-Captions": "Subtítulos automáticos",
  "AI Editor": "Editor con IA",
  "AI Editor chat": "Chat del editor con IA",
  "AI Highlights": "Mejores momentos",
  "AI cloud jobs are unavailable in this environment.": "Las tareas de IA en la nube no están disponibles acá.",
  "AI edit request": "Petición de edición",
  "AI voice generation": "Generación de voz con IA",
  "AI-Powered Tools": "Herramientas con IA",
  "API Key Settings": "Ajustes de llaves",
  "API key": "Llave de API",
  Acceleration: "Aceleración",
  "Accepts .json project files": "Acepta archivos .json de proyecto",
  Add: "Añadir",
  "Add API Key": "Añadir llave",
  "Add Adjustment Layer": "Añadir capa de ajuste",
  "Add Custom Sticker": "Añadir pegatina propia",
  "Add Effect": "Añadir efecto",
  "Add Freeze Frame at Playhead": "Congelar cuadro en el cabezal",
  "Add Layer": "Añadir capa",
  "Add Mask Shape": "Añadir forma de máscara",
  "Add Scene": "Añadir escena",
  "Add an audio track to use auto-edit": "Añade una pista de audio para el montaje automático",
  "Add another audio or video track with speech to use as trigger": "Añade otra pista con voz para usarla de disparador",
  "Add clips to the timeline to estimate a compressed size.": "Añade clips a la línea de tiempo para estimar el tamaño.",
  "Add color": "Añadir color",
  "Add custom path mask": "Añadir máscara de trazado",
  "Add fun elements to your video": "Añade elementos divertidos",
  "Add new layer": "Añadir capa nueva",
  "Add path point": "Añadir punto",
  "Add point": "Añadir punto",
  "Add scene": "Añadir escena",
  "Add to Timeline": "Añadir a la línea de tiempo",
  "Add video effect": "Añadir efecto de video",
  "Adjustment Layers": "Capas de ajuste",
  "Advanced Options": "Opciones avanzadas",
  Algorithm: "Algoritmo",
  Align: "Alinear",
  "Align Bottom": "Alinear abajo",
  "Align Left": "Alinear a la izquierda",
  "Align Right": "Alinear a la derecha",
  "Align Top": "Alinear arriba",
  "Align positions bottom": "Alinear abajo",
  "Align positions center": "Alinear al centro",
  "Align positions left": "Alinear a la izquierda",
  "Align positions middle": "Alinear al medio",
  "Align positions right": "Alinear a la derecha",
  "Align positions top": "Alinear arriba",
  "Align to Canvas": "Alinear al lienzo",
  Alignment: "Alineación",
  All: "Todo",
  "All Beats": "Todos los beats",
  Amount: "Cantidad",
  Amplitude: "Amplitud",
  "Analyzing beats...": "Analizando el beat…",
  "Analyzing frames...": "Analizando cuadros…",
  "Anchor Point": "Punto de anclaje",
  Angle: "Ángulo",
  "Angle offset": "Desfase del ángulo",
  "Animate Property": "Animar propiedad",
  "Animate property": "Animar propiedad",
  Animation: "Animación",
  "Animation Preset": "Animación",
  "Animation Style": "Estilo de animación",
  "Animation style": "Estilo de animación",
  Appearance: "Apariencia",
  "Append effects to selection": "Añadir efectos a la selección",
  "Applied Animations": "Animaciones aplicadas",
  Apply: "Aplicar",
  "Apply Auto-Edit": "Aplicar montaje automático",
  "Apply Entry/Exit Animations": "Aplicar animaciones de entrada y salida",
  "Apply Template": "Aplicar plantilla",
  "Apply Tracking to Clip": "Aplicar el seguimiento al clip",
  "Apply Transition": "Aplicar transición",
  "Apply cinematic color grades instantly": "Aplica gradaciones de color al instante",
  "Apply color, effects to all clips below": "Aplica color y efectos a todo lo que esté debajo",
  "Apply speed to audio": "Aplicar la velocidad al audio",
  "Applying...": "Aplicando…",
  Approve: "Aprobar",
  "Approve all this turn": "Aprobar todo este turno",
  Arguments: "Argumentos",
  "Ask the AI to edit your video…": "Pídele a la IA que edite tu video…",
  "Aspect Ratio": "Proporción",
  "Aspect ratio": "Proporción",
  Attack: "Ataque",
  "Audio Ducking": "Atenuación de música",
  "Audio Effects": "Efectos de audio",
  "Audio Mixer": "Mezclador de audio",
  "Audio Mixing Console": "Consola de mezcla",
  "Audio Settings": "Ajustes de audio",
  "Audio Source": "Fuente de audio",
  "Audio bitrate": "Tasa de bits del audio",
  "Audio format": "Formato de audio",
  "Author Name": "Autor",
  "Auto Captions": "Subtítulos automáticos",
  "Auto Cut Silence": "Cortar silencios",
  "Auto Orient": "Orientar solo",
  "Auto Reframe": "Reencuadre automático",
  "Auto-Caption": "Subtítulos automáticos",
  "Auto-Cut on Every 4 Beats": "Cortar cada 4 beats",
  "Auto-Save": "Autoguardado",
  "Auto-allow destructive actions": "Permitir acciones destructivas sin preguntar",
  "Auto-lower music when speech plays": "Baja la música sola cuando alguien habla",
  "Auto-save interval": "Intervalo de autoguardado",
  "Automate your editing with intelligent features": "Automatiza tu edición",
  "Automatically generate subtitles from audio": "Genera subtítulos a partir del audio",
  "Automatically reduces music volume when voice is detected": "Baja la música al detectar voz",
  "Automatically save your project at regular intervals": "Guarda tu proyecto cada cierto tiempo",
  "Available Workflows": "Flujos disponibles",
  "BPM Detected": "BPM detectados",
  Back: "Atrás",
  "Back to AI Tools": "Volver a las herramientas de IA",
  "Back to Templates": "Volver a plantillas",
  "Back to model selection": "Volver a elegir modelo",
  Background: "Fondo",
  "Background Color": "Color de fondo",
  "Background Image": "Imagen de fondo",
  "Background Mode": "Modo de fondo",
  "Background Removal": "Quitar fondo",
  "Background fill": "Relleno de fondo",
  "Background opacity": "Opacidad del fondo",
  Backgrounds: "Fondos",
  "Batch Effects": "Efectos en lote",
  "Batch Text": "Texto en lote",
  "Batch Transform": "Transformar en lote",
  "Batch changes stay synchronized with the timeline": "Los cambios en lote siguen sincronizados con la línea de tiempo",
  "Beat Markers": "Marcas de beat",
  "Beat Subdivision": "Subdivisión del beat",
  "Beat Sync": "Sincronizar con el beat",
  "Beat detection progress": "Progreso de la detección",
  "Beat-Synced Auto-Edit": "Montaje automático al beat",
  Beats: "Beats",
  Before: "Antes",
  "Best match": "Mejor coincidencia",
  Better: "Mejor",
  "Bevel Segments": "Segmentos del bisel",
  "Bevel Size": "Tamaño del bisel",
  "Bevel Thickness": "Grosor del bisel",
  "Bitrate (kbps)": "Tasa de bits (kbps)",
  "Blend Mode": "Modo de fusión",
  "Blend Opacity": "Opacidad de fusión",
  "Blend mode": "Modo de fusión",
  Blending: "Fusión",
  Blur: "Desenfoque",
  "Blur Amount": "Cantidad de desenfoque",
  "Blur Strength": "Fuerza del desenfoque",
  "Blur background fill": "Fondo desenfocado",
  Bold: "Negrita",
  "Border Radius": "Radio del borde",
  "Bounce Settings": "Ajustes del rebote",
  Bounces: "Rebotes",
  "Browse royalty-free audio for your projects": "Busca audio libre de regalías",
  "Browse templates": "Ver plantillas",
  "Browser Not Supported": "Navegador no compatible",
  "Brush Settings": "Ajustes del pincel",
  "Built-in": "De fábrica",
  "Burn Intensity": "Intensidad del quemado",
  "Camera Groups": "Grupos de cámaras",
  "Camera angle name": "Nombre del ángulo",
  "Cancel Tracking": "Cancelar seguimiento",
  "Cancel recording": "Cancelar grabación",
  "Cancel rename": "Cancelar",
  "Canvas snapping": "Ajuste al lienzo",
  "Caption Style": "Estilo de subtítulo",
  "Caption generation progress": "Progreso de los subtítulos",
  Category: "Categoría",
  "Center & Full": "Centro y completo",
  "Center Bias": "Sesgo al centro",
  "Center Both": "Centrar en ambos",
  "Center Horizontally": "Centrar en horizontal",
  "Center Vertically": "Centrar en vertical",
  "Center X": "Centro X",
  "Center Y": "Centro Y",
  "Center on Canvas": "Centrar en el lienzo",
  "Change Password": "Cambiar contraseña",
  Channel: "Canal",
  "Choose Image": "Elegir imagen",
  "Choose a video to compress...": "Elige un video para comprimir…",
  "Choose custom sticker image": "Elegir imagen de pegatina",
  "Chroma Key (Green Screen)": "Chroma (fondo verde)",
  Clear: "Limpiar",
  "Clear All": "Limpiar todo",
  "Clear Beat Markers": "Quitar marcas de beat",
  "Clear SVG import error": "Limpiar el error de importación",
  "Clear all saved projects": "Borrar todos los proyectos guardados",
  "Clear conversation": "Limpiar conversación",
  "Clear effect stack": "Quitar los efectos",
  "Clear effects from selection": "Quitar los efectos",
  "Clear error": "Limpiar error",
  "Clear path": "Limpiar trazado",
  "Clear search": "Limpiar búsqueda",
  "Click a shape above to add a mask": "Haz clic en una forma de arriba para añadir una máscara",
  "Click on the video preview to pick a color": "Haz clic en la vista previa para tomar un color",
  "Click or drag & drop": "Haz clic o arrastra",
  "Click to add text to timeline": "Haz clic para añadir el texto a la línea de tiempo",
  "Click to select": "Haz clic para seleccionar",
  "Client Setup": "Configuración del cliente",
  "Clip Audio": "Audio del clip",
  "Clip not found": "No encuentro el clip",
  "Clip-to-Clip Transitions": "Transiciones entre clips",
  "Clip-to-clip transitions are available for timeline media clips.": "Las transiciones entre clips sirven para clips de la línea de tiempo.",
  Clips: "Clips",
  Clockwise: "Sentido horario",
  "Clone Source": "Origen del clonado",
  Cloned: "Clonadas",
  "Close action history": "Cerrar historial",
  "Close creation review": "Cerrar la revisión",
  "Close keyframe editor": "Cerrar el editor de keyframes",
  "Close mixer": "Cerrar mezclador",
  Cloud: "Nube",
  "Cloud GPU Tools": "Herramientas de GPU en la nube",
  Codec: "Códec",
  Codecs: "Códecs",
  Color: "Color",
  "Color Grading": "Gradación de color",
  "Color Wheels": "Ruedas de color",
  Colors: "Colores",
  "Compact tracks": "Pistas compactas",
  "Composition grid": "Rejilla de composición",
  "Compound Clip": "Clip compuesto",
  "Compound Clips Library": "Biblioteca de clips compuestos",
  "Compound clip name": "Nombre del clip compuesto",
  Compress: "Comprimir",
  "Compress Video": "Comprimir video",
  "Compress video...": "Comprimir video…",
  "Compression progress": "Progreso de la compresión",
  Compressor: "Compresor",
  Confidence: "Confianza",
  "Confidence Threshold": "Umbral de confianza",
  "Configure preferences and manage API keys for external services.": "Configura preferencias y gestiona las llaves de servicios externos.",
  "Configure template variables": "Configurar las variables",
  "Confirm New Password": "Confirmar la nueva",
  "Confirm action": "Confirmar",
  "Confirm rename": "Confirmar",
  "Content Generation": "Generación de contenido",
  "Control visible regions of clip": "Controla qué partes del clip se ven",
  "Copy URL": "Copiar URL",
  "Copy config": "Copiar configuración",
  "Copy effect stack": "Copiar los efectos",
  "Copy first effect stack": "Copiar los efectos del primero",
  "Copy token": "Copiar token",
  "Corner Positions": "Posiciones de esquina",
  Corners: "Esquinas",
  "Create Compound Clip": "Crear clip compuesto",
  "Create Motion Scene": "Crear escena de movimiento",
  "Create New Group": "Crear grupo",
  "Create Snapshot": "Crear instantánea",
  "Create compound clips from selections": "Crea clips compuestos a partir de la selección",
  "Create with KieAI": "Crear con KieAI",
  "Creation Review": "Revisión",
  Crop: "Recorte",
  "Crop Video": "Recortar video",
  "Crop preview": "Vista previa del recorte",
  "Current Password": "Contraseña actual",
  "Current Project": "Proyecto actual",
  "Current Settings": "Ajustes actuales",
  Curves: "Curvas",
  Custom: "A medida",
  "Custom Font": "Tipografía propia",
  "Custom Speed": "Velocidad a medida",
  "Custom export...": "Exportación a medida…",
  "Custom target size": "Tamaño objetivo a medida",
  "Customize Template": "Personalizar plantilla",
  "Cut Mode": "Modo de corte",
  Damping: "Amortiguación",
  "Decrease rotation": "Reducir rotación",
  "Default AI Providers": "Proveedores de IA por defecto",
  Delay: "Retardo",
  "Delete (Del)": "Borrar (Supr)",
  "Delete Mask": "Borrar máscara",
  "Delete Subtitle": "Borrar subtítulo",
  "Delete camera group": "Borrar grupo de cámaras",
  "Delete key": "Borrar llave",
  "Delete keyframe": "Borrar keyframe",
  "Delete selected clips": "Borrar los clips seleccionados",
  "Delete track": "Borrar pista",
  Depth: "Profundidad",
  "Describe the image you want to generate...": "Describe la imagen que quieres generar…",
  "Describe what this template is for and how to use it...": "Describe para qué sirve y cómo se usa…",
  "Describe what you don't want in the result...": "Describe lo que NO quieres…",
  Description: "Descripción",
  "Desktop only": "Solo en computador",
  "Detect Beats": "Detectar beats",
  "Detect Beats from Audio": "Detectar el beat del audio",
  "Detected BPM": "BPM detectados",
  "Detection Threshold": "Umbral de detección",
  Direction: "Dirección",
  Discard: "Descartar",
  "Dismiss notification": "Descartar aviso",
  Distance: "Distancia",
  "Distribute horizontally": "Distribuir en horizontal",
  "Distribute vertically": "Distribuir en vertical",
  Downbeats: "Tiempos fuertes",
  "Downbeats Only": "Solo tiempos fuertes",
  Download: "Descargar",
  "Download JSON": "Descargar JSON",
  "Drag clip in preview to fine-tune position": "Arrastra el clip en la vista previa para afinarlo",
  "Drag to adjust color. Double-click to reset.": "Arrastra para ajustar el color. Doble clic para restablecer.",
  "Drag to move": "Arrastra para mover",
  "Drag to move shape": "Arrastra para mover la forma",
  "Drag to move text": "Arrastra para mover el texto",
  "Drag to reorder effect": "Arrastra para reordenar",
  "Draw a box around the object to track across the clip.": "Dibuja un recuadro sobre el objeto que quieres rastrear.",
  "Draw region in preview or enter coordinates": "Dibuja la región en la vista previa o escribe las coordenadas",
  "Drop a JSON file here or click to browse": "Suelta un archivo JSON acá o haz clic para buscarlo",
  "Drop files to import": "Suelta archivos para importar",
  "Drop to add clip": "Suelta para añadir el clip",
  "Ducking Applied": "Atenuación aplicada",
  "Ducking Presets": "Ajustes de atenuación",
  "Duplicate (⌘D)": "Duplicar (⌘D)",
  "Duplicate Mask": "Duplicar máscara",
  "Duplicate effect": "Duplicar efecto",
  Easing: "Suavizado",
  "Edge Smoothing": "Suavizado de bordes",
  "Edge Softness": "Suavidad del borde",
  Edit: "Editar",
  "Edit by chatting": "Editar conversando",
  "Edit recipe controls": "Editar los controles",
  "Editor tools": "Herramientas del editor",
  Effect: "Efecto",
  "Effect categories": "Categorías de efectos",
  "Emission Rate": "Tasa de emisión",
  Emojis: "Emojis",
  "Emphasis Animation": "Animación de énfasis",
  "Emphasis x": "Énfasis x",
  Enable: "Activar",
  "Enable Green Screen": "Activar fondo verde",
  "Enable auto-save": "Activar autoguardado",
  "Enable to remove background color": "Actívalo para quitar el color de fondo",
  "End Opacity": "Opacidad final",
  "End Time": "Fin",
  "Enhance Quality (Upscaling)": "Mejorar calidad (escalado)",
  "Enhance for TTS": "Mejorar para voz",
  "Enhanced - edit below then Generate": "Mejorado — edita abajo y genera",
  "Enhanced preview": "Vista previa mejorada",
  "Enter current password": "Escribe la contraseña actual",
  "Enter subtitle text...": "Escribe el subtítulo…",
  "Enter text...": "Escribe el texto…",
  "Enter the text you want to convert to speech...": "Escribe el texto que quieres convertir en voz…",
  "Enter your master password to view and manage API keys.": "Escribe tu contraseña maestra para ver y gestionar las llaves.",
  "Entry Animation": "Animación de entrada",
  "Entry x": "Entrada x",
  Equalizer: "Ecualizador",
  Errors: "Errores",
  "Estimated output": "Salida estimada",
  "Exit Animation": "Animación de salida",
  "Exit x": "Salida x",
  "Expand each side": "Expandir cada lado",
  Expansion: "Expansión",
  "Export Progress": "Progreso de la exportación",
  "Export as H.264 anyway": "Exportar en H.264 de todas formas",
  "Export mode": "Modo de exportación",
  "Export or import project as JSON": "Exportar o importar el proyecto como JSON",
  "Exporting Video": "Exportando video",
  "Fade Settings": "Ajustes del fundido",
  "Fade in": "Entrada gradual",
  "Fade out": "Salida gradual",
  Failed: "Falló",
  Favorites: "Favoritos",
  Feather: "Difuminado",
  Feathering: "Difuminado",
  Featured: "Destacados",
  Feedback: "Realimentación",
  Fill: "Relleno",
  "Filter Presets": "Filtros",
  "Fit Mode": "Modo de ajuste",
  "Flash Intensity": "Intensidad del destello",
  Flatten: "Aplanar",
  Flow: "Flujo",
  "Focus Point": "Punto de enfoque",
  "Focus Zoom Settings": "Ajustes del zoom",
  "Fold Shadow": "Sombra del pliegue",
  "Follow Subject": "Seguir al sujeto",
  Font: "Tipografía",
  "Font Family": "Tipografía",
  "Font Size": "Tamaño de letra",
  "Font family": "Tipografía",
  "For Your Video": "Para tu video",
  "Frame Rate": "Cuadros por segundo",
  Frequency: "Frecuencia",
  From: "Desde",
  "From idea to export.": "De la idea a la entrega.",
  "Full settings with AI upscaling": "Ajustes completos con escalado por IA",
  "Gain (Highlights)": "Altas luces (gain)",
  "Gamma (Midtones)": "Medios (gamma)",
  "Generate Captions": "Generar subtítulos",
  "Generate captions from speech": "Genera subtítulos a partir de la voz",
  "Generate natural voiceovers from text": "Genera locuciones naturales a partir de texto",
  "Generating scope data...": "Generando los datos…",
  "Generating…": "Generando…",
  "Get accurate estimate": "Calcular con precisión",
  "Glitch Settings": "Ajustes del glitch",
  Gravity: "Gravedad",
  "Green Screen": "Fondo verde",
  "Group clips into reusable compound clips": "Agrupa clips en compuestos reutilizables",
  Hardness: "Dureza",
  "Hardware accelerated": "Acelerado por hardware",
  "Hear Cleaned": "Oír el limpio",
  "Hear Original": "Oír el original",
  Height: "Alto",
  "Higher = more accurate but may lose track easier": "Más alto = más preciso, pero pierde el rastro más fácil",
  "Highlight Color": "Color de resaltado",
  Highlights: "Altas luces",
  Histogram: "Histograma",
  History: "Historial",
  "Hold Duration": "Duración de la pausa",
  "Hold Time": "Tiempo de espera",
  Horizontal: "Horizontal",
  "How fast volume drops when voice starts": "Qué tan rápido baja al empezar la voz",
  "How fast volume returns after voice stops": "Qué tan rápido vuelve al terminar",
  "How much to lower background music": "Cuánto baja la música de fondo",
  "How to use": "Cómo se usa",
  Hue: "Tono",
  "Image loaded": "Imagen cargada",
  "Import Project": "Importar proyecto",
  "Import SRT File": "Importar SRT",
  "Import SRT file": "Importar archivo SRT",
  "Import SVG": "Importar SVG",
  "Import SVG File": "Importar archivo SVG",
  "Import SVG file": "Importar archivo SVG",
  "Import custom stickers below": "Importa pegatinas propias abajo",
  "Import media": "Importar material",
  "Import media to use here": "Importa material para usarlo acá",
  "Import video clips to use multi-camera editing": "Importa clips para editar en multicámara",
  "Importing...": "Importando…",
  "In Duration": "Duración de entrada",
  "In your browser.": "En tu navegador.",
  "Increase rotation": "Aumentar rotación",
  Inspector: "Propiedades",
  "Inspector tabs": "Pestañas de propiedades",
  Intensity: "Intensidad",
  Italic: "Cursiva",
  "Its clips will be removed. You can undo this action.": "Se quitarán sus clips. Puedes deshacerlo.",
  "Keep Current": "Dejar como está",
  "Key Color": "Color clave",
  "Keyboard Shortcuts": "Atajos de teclado",
  "Keyframe Editor": "Editor de keyframes",
  "Keyframe editor": "Editor de keyframes",
  "Keyframe value": "Valor del keyframe",
  Keyframes: "Keyframes",
  "KieAI generation in progress…": "Generando con KieAI…",
  "LLM model": "Modelo",
  "LLM provider": "Proveedor del modelo",
  Language: "Idioma",
  "Large tracks": "Pistas grandes",
  "Layer Properties": "Propiedades de la capa",
  "Learned noise profile is active on this clip.": "El perfil de ruido aprendido está activo en este clip.",
  "Letter Spacing": "Espaciado entre letras",
  "Lift (Shadows)": "Sombras (lift)",
  "Line Height": "Interlineado",
  "Live preview": "Vista previa en vivo",
  "Load Different LUT": "Cargar otro LUT",
  "Load LUT file": "Cargar archivo LUT",
  "Loading AI model...": "Cargando el modelo…",
  "Loading frame...": "Cargando el cuadro…",
  "Loading photo...": "Cargando la foto…",
  "Loading recent projects...": "Cargando proyectos recientes…",
  "Loading templates...": "Cargando plantillas…",
  "Loading video...": "Cargando el video…",
  Local: "Local",
  "Loop Animation": "Animación en bucle",
  "Lower values detect more silence": "Valores más bajos detectan más silencio",
  Luminance: "Luminancia",
  "MCP Server": "Servidor MCP",
  "Manage track layers": "Gestionar capas",
  "Manual BPM": "BPM manual",
  "Marker label": "Etiqueta del marcador",
  Markers: "Marcadores",
  Masking: "Máscaras",
  "Masks control which parts of the clip are visible": "Las máscaras controlan qué se ve del clip",
  "Master volume fader": "Volumen general",
  "Match Video": "Ajustar al video",
  "Match Video Dimensions?": "¿Ajustar al tamaño del video?",
  "Matte source": "Origen de la máscara",
  "Max Size": "Tamaño máximo",
  "Max duration": "Duración máxima",
  "Maximum Offset": "Desplazamiento máximo",
  "Maximum Pixel Size": "Tamaño máximo de píxel",
  "Media Library": "Biblioteca",
  Metalness: "Metalicidad",
  Microphone: "Micrófono",
  Midpoint: "Punto medio",
  Midtones: "Medios",
  "Min Clip Duration": "Duración mínima",
  "Min Duration": "Duración mínima",
  "Min Size": "Tamaño mínimo",
  "Minimize controls": "Minimizar controles",
  "Minimum clip duration": "Duración mínima del clip",
  "Minimum silence length to detect": "Silencio mínimo que se detecta",
  "Minimum time to stay ducked between words": "Tiempo mínimo atenuado entre palabras",
  Missing: "Falta",
  Mixed: "Mezclado",
  Mode: "Modo",
  Model: "Modelo",
  "Motion Blur": "Desenfoque de movimiento",
  "Motion Path": "Trayectoria",
  "Motion Presets": "Ajustes de movimiento",
  "Motion Scene": "Escena de movimiento",
  "Motion Tracking": "Seguimiento de movimiento",
  "Multi-Camera Editing": "Edición multicámara",
  Music: "Música",
  "Music & SFX": "Música y efectos",
  "Music & Sound Effects": "Música y efectos de sonido",
  "My Awesome Template": "Mi plantilla",
  "My Awesome Video": "Mi video",
  Navigate: "Navegar",
  "Navigate between sections": "Moverse entre secciones",
  "Negative Prompt (optional)": "Instrucción negativa (opcional)",
  "Nested Sequences": "Secuencias anidadas",
  "New Project": "Proyecto nuevo",
  Next: "Siguiente",
  "Next scene": "Escena siguiente",
  "No Recent Projects": "No hay proyectos recientes",
  "No SVG clip selected": "Ningún SVG seleccionado",
  "No actions yet": "Todavía no hay acciones",
  "No adjacent clips are available on this track.": "No hay clips contiguos en esta pista.",
  "No background fill": "Sin relleno de fondo",
  "No clip selected": "Ningún clip seleccionado",
  "No effects applied": "Sin efectos",
  "No effects found": "No hay efectos",
  "No emojis found": "No hay emojis",
  "No frame to analyze": "No hay cuadro que analizar",
  "No keyframes": "Sin keyframes",
  "No keyframes for this property. Add one to start animating.": "Esta propiedad no tiene keyframes. Añade uno para empezar.",
  "No layers": "No hay capas",
  "No markers yet": "Todavía no hay marcadores",
  "No masks on this clip": "Este clip no tiene máscaras",
  "No media available": "No hay material",
  "No other tracks with clips found. Add clips to other tracks first.": "No hay otras pistas con clips. Añade clips a otras pistas primero.",
  "No particle effects added": "No hay efectos de partículas",
  "No project data to export.": "No hay datos que exportar.",
  "No recipes match": "No hay recetas",
  "No shape clip selected": "Ninguna forma seleccionada",
  "No shortcuts found": "No hay atajos",
  "No snapshots saved": "No hay instantáneas",
  "No sounds found": "No hay sonidos",
  "No stickers yet": "Todavía no hay pegatinas",
  "No templates found": "No hay plantillas",
  "No templates in this category": "No hay plantillas en esta categoría",
  "No text clip selected": "Ningún texto seleccionado",
  "No tracks match your filters": "Ninguna pista coincide con los filtros",
  "No tracks yet": "Todavía no hay pistas",
  "Noise Reduction": "Reducción de ruido",
  "Noise analysis progress": "Progreso del análisis de ruido",
  "Non-destructive effects on clips below": "Efectos no destructivos sobre los clips de abajo",
  None: "Ninguno",
  Notifications: "Avisos",
  Nudge: "Mover",
  "Nudge clips down": "Mover clips abajo",
  "Nudge clips left": "Mover clips a la izquierda",
  "Nudge clips right": "Mover clips a la derecha",
  "Nudge clips up": "Mover clips arriba",
  "Nudge position by one pixel": "Mover un píxel",
  Offset: "Desfase",
  "Offset X": "Desplazamiento X",
  "Offset Y": "Desplazamiento Y",
  "One-click color grades": "Gradaciones en un clic",
  "Open Settings": "Abrir ajustes",
  "Open editor": "Abrir el editor",
  "Optional: describe what you want to change or emphasize...": "Opcional: describe qué cambiar o destacar…",
  "Other Layers": "Otras capas",
  "Out Duration": "Duración de salida",
  "Overall Progress": "Progreso total",
  "Overall progress": "Progreso total",
  Overshoot: "Sobrepaso",
  "Pad After": "Respiro después",
  "Pad Before": "Respiro antes",
  "Pan control": "Control de panorama",
  Parameters: "Parámetros",
  "Particle Count": "Número de partículas",
  "Particle Effects": "Partículas",
  "Particle Settings": "Ajustes de partículas",
  "Particle effect preset": "Ajuste de partículas",
  "Particle preset previews": "Vistas previas de partículas",
  "Paste and replace effects": "Pegar y reemplazar",
  "Paste effect stack": "Pegar los efectos",
  "Paste your API key here": "Pega acá tu llave de API",
  "Path Points": "Puntos del trazado",
  "Path Smoothing": "Suavizado de trayectoria",
  "Path Type": "Tipo de trazado",
  "Path points": "Puntos del trazado",
  "Pause recording": "Pausar grabación",
  Perspective: "Perspectiva",
  "Pick a clip...": "Elige un clip…",
  "Pick a format and start creating. You can change this anytime.": "Elige un formato y empieza. Puedes cambiarlo cuando quieras.",
  "Pick color from video": "Tomar color del video",
  "Picture-in-Picture": "Imagen en imagen",
  "Pitch Correct": "Corregir tono",
  "Place Behind Subject": "Poner detrás del sujeto",
  "Place video clips below this one to use as background": "Pon clips debajo de este para usarlos de fondo",
  "Platform Presets": "Ajustes por plataforma",
  "Playback Speed": "Velocidad de reproducción",
  "Playback quality": "Calidad de reproducción",
  "Please wait while effects are being applied...": "Espera mientras se aplican los efectos…",
  "Pop Settings": "Ajustes del pop",
  "Position Offset": "Desplazamiento",
  "Position and scale video overlay": "Coloca y escala la superposición",
  "Position on Canvas": "Posición en el lienzo",
  Preserve: "Conservar",
  Presets: "Ajustes",
  "Press M at playhead to add markers": "Pulsa M en el cabezal para marcar",
  "Press keys...": "Pulsa las teclas…",
  Preview: "Vista previa",
  "Preview Zoom": "Zoom de la vista previa",
  "Preview canvas": "Lienzo de vista previa",
  "Preview effect": "Ver el efecto",
  "Preview highlight": "Ver el momento",
  "Preview only. Export still uses the cleaned audio effect chain.": "Solo vista previa. La exportación usa el audio limpio.",
  "Preview voice": "Escuchar la voz",
  Previous: "Anterior",
  "Previous scene": "Escena anterior",
  "Pro Tips": "Consejos",
  "Processing Effects": "Aplicando efectos",
  Progress: "Progreso",
  "Project Composition": "Composición del proyecto",
  "Project JSON": "JSON del proyecto",
  "Project JSON / Comments": "JSON del proyecto / comentarios",
  "Project JSON file": "Archivo JSON del proyecto",
  "Project Name": "Nombre del proyecto",
  "Project name": "Nombre del proyecto",
  Prompt: "Instrucción",
  "Prompt (optional)": "Instrucción (opcional)",
  Property: "Propiedad",
  Provider: "Proveedor",
  "Push Out": "Empujar",
  "Quality Mode": "Modo de calidad",
  "Quick Actions": "Acciones rápidas",
  "Quick Export Match Source": "Exportación rápida igual al origen",
  Radius: "Radio",
  Randomness: "Aleatoriedad",
  Ratio: "Proporción",
  "Re-analyze Beats": "Volver a analizar",
  "Re-stabilize": "Volver a estabilizar",
  "Re-track with Different Settings": "Volver a rastrear con otros ajustes",
  "Recent Projects": "Proyectos recientes",
  "Recent projects": "Proyectos recientes",
  "Recent projects are stored locally in your browser": "Los proyectos recientes se guardan en tu navegador",
  "Recommendation ready": "Recomendación lista",
  Recording: "Grabando",
  "Recording Error": "Error de grabación",
  "Recording will start after a 3-second countdown": "La grabación empieza tras una cuenta de 3",
  "Recording...": "Grabando…",
  "Recover Your Work": "Recuperar tu trabajo",
  "Redo (⇧⌘Z)": "Rehacer (⇧⌘Z)",
  "Reduce by": "Reducir en",
  "Reduces jitter in tracking path": "Reduce el temblor del seguimiento",
  Reduction: "Reducción",
  Reject: "Rechazar",
  Release: "Caída",
  "Relink from Folder": "Volver a enlazar desde carpeta",
  Remake: "Rehacer",
  Remove: "Quitar",
  "Remove All Effects": "Quitar todos los efectos",
  "Remove Background": "Quitar el fondo",
  "Remove LUT": "Quitar LUT",
  "Remove Tracking": "Quitar seguimiento",
  "Remove Transition": "Quitar transición",
  "Remove angle": "Quitar ángulo",
  "Remove background color from video": "Quita el color de fondo del video",
  "Remove color": "Quitar color",
  "Remove effect": "Quitar efecto",
  "Remove freeze frame": "Quitar congelado",
  "Remove from recent": "Quitar de recientes",
  "Remove marker": "Quitar marcador",
  "Remove recipe": "Quitar receta",
  "Remove speed keyframe": "Quitar keyframe de velocidad",
  "Remove transition": "Quitar transición",
  Rename: "Renombrar",
  "Rename project": "Renombrar proyecto",
  "Repeat new password": "Repite la contraseña nueva",
  "Replace asset": "Reemplazar archivo",
  "Replace effects on selection": "Reemplazar los efectos",
  Reset: "Restablecer",
  "Reset All": "Restablecer todo",
  "Reset Crop": "Restablecer recorte",
  "Reset Speed & Effects": "Restablecer velocidad y efectos",
  "Reset crop": "Restablecer recorte",
  "Reset to Default": "Volver al valor por defecto",
  "Reset to Defaults": "Volver a los valores por defecto",
  "Reset to default": "Volver al valor por defecto",
  "Reset to full clip": "Volver al clip completo",
  "Reset transforms": "Restablecer transformaciones",
  "Reset white balance": "Restablecer el balance",
  Result: "Resultado",
  "Resume recording": "Reanudar grabación",
  "Retouching Tools": "Herramientas de retoque",
  Retry: "Reintentar",
  "Retry generation": "Reintentar generación",
  Reverb: "Reverberación",
  Reverse: "Reversa",
  "Ripple delete (⇧Del)": "Borrar y cerrar hueco (⇧Supr)",
  "Room Size": "Tamaño de sala",
  "Rotate Settings": "Ajustes de rotación",
  "Rotate token": "Rotar token",
  "Rotation X": "Rotación X",
  "Rotation Y": "Rotación Y",
  "Rotation Z": "Rotación Z",
  Rotations: "Vueltas",
  Roughness: "Rugosidad",
  "Royalty-free sounds": "Sonidos libres de regalías",
  "SVG Import": "Importar SVG",
  "SVG Properties": "Propiedades del SVG",
  "SVG imported successfully": "SVG importado",
  "Sample rate": "Frecuencia de muestreo",
  Saturation: "Saturación",
  "Save Current Project as Template": "Guardar este proyecto como plantilla",
  "Save Key": "Guardar llave",
  "Save Location": "Dónde guardar",
  "Save as Template": "Guardar como plantilla",
  "Save every": "Guardar cada",
  "Save project name": "Guardar el nombre",
  "Save to Media": "Guardar en el material",
  "Saved!": "Guardado",
  "Scale From": "Escala desde",
  "Scale Settings": "Ajustes de escala",
  "Scale To": "Escala hasta",
  "Scene Navigator": "Navegador de escenas",
  Scenes: "Escenas",
  "Screen Recording": "Grabación de pantalla",
  "Screen recording not supported": "Este navegador no graba pantalla",
  "Search Effects": "Buscar efectos",
  "Search by name, accent, gender...": "Busca por nombre, acento o género…",
  "Search effects": "Buscar efectos",
  "Search recipes": "Buscar recetas",
  "Search recipes...": "Buscar recetas…",
  "Search shortcuts": "Buscar atajos",
  "Search shortcuts...": "Buscar atajos…",
  "Search sounds": "Buscar sonidos",
  "Search sounds...": "Buscar sonidos…",
  "Search templates": "Buscar plantillas",
  "Search templates...": "Buscar plantillas…",
  "Search tools, effects, or ask AI": "Busca herramientas, efectos o pregúntale a la IA",
  "Search track layers": "Buscar capas",
  "Search tracks": "Buscar pistas",
  "Search transitions": "Buscar transiciones",
  "Search visual effects": "Buscar efectos visuales",
  "Search voices": "Buscar voces",
  "Secure API Key Storage": "Guardado seguro de llaves",
  "Segments Found": "Segmentos encontrados",
  Select: "Elegir",
  "Select Format": "Elegir formato",
  "Select a clip first": "Elige un clip primero",
  "Select a clip to apply motion presets": "Elige un clip para aplicar movimiento",
  "Select a clip with keyframes to edit": "Elige un clip con keyframes para editarlo",
  "Select a model to generate a new image from your source.": "Elige un modelo para generar una imagen nueva.",
  "Select a preset above to add effects": "Elige un ajuste de arriba",
  "Select a property to animate": "Elige una propiedad para animarla",
  "Select a template to edit variables": "Elige una plantilla para editar sus variables",
  "Select a video clip to apply filters": "Elige un clip para aplicar filtros",
  "Select a video or audio clip to analyze beats": "Elige un clip de video o audio para analizar el beat",
  "Select effect preset...": "Elige un ajuste…",
  "Select highlight color": "Color de resaltado",
  "Select replacement background color": "Color de fondo de reemplazo",
  "Select subtitle background color": "Color de fondo del subtítulo",
  "Select subtitle text color": "Color del texto del subtítulo",
  "Selected clips rotation": "Rotación de los clips",
  "Selected photo": "Foto seleccionada",
  "Selection Actions": "Acciones sobre la selección",
  Send: "Enviar",
  Sensitivity: "Sensibilidad",
  "Session Locked": "Sesión bloqueada",
  "Shader Fill": "Relleno por shader",
  "Shader effect previews": "Vistas previas de shaders",
  Shadow: "Sombra",
  Shadows: "Sombras",
  "Shake Settings": "Ajustes del temblor",
  "Shape Properties": "Propiedades de la forma",
  "Shape clip": "Clip de forma",
  Shapes: "Formas",
  Sharpening: "Nitidez",
  "Show Only Missing Assets": "Ver solo los que faltan",
  "Show Path": "Ver trazado",
  "Show device export estimate details": "Ver el detalle del cálculo",
  "Shrink any video to a target size": "Reduce cualquier video a un tamaño objetivo",
  "Silence Threshold": "Umbral de silencio",
  "Silent Sections Found": "Silencios encontrados",
  "Single-Clip Transitions": "Transiciones de un solo clip",
  "Single-clip transitions are available for video and image clips.": "Las transiciones de un solo clip sirven para video e imagen.",
  Size: "Tamaño",
  "Skip Tour": "Saltar recorrido",
  "Skip back 5s": "Atrás 5 s",
  "Skip forward 5s": "Adelante 5 s",
  "Skip on startup": "Saltar al arrancar",
  "Skip tour": "Saltar recorrido",
  Slats: "Láminas",
  Slices: "Cortes",
  "Slide Settings": "Ajustes del deslizamiento",
  Smaller: "Más pequeño",
  "Smooth Slow Motion": "Cámara lenta suave",
  Smoothing: "Suavizado",
  "Snapshot name": "Nombre de la instantánea",
  "Snapshot name...": "Nombre de la instantánea…",
  Softness: "Suavidad",
  "Something went wrong": "Algo salió mal",
  "Sort media": "Ordenar material",
  "Sound FX": "Efectos de sonido",
  Source: "Origen",
  "Source image": "Imagen de origen",
  "Speed & Direction": "Velocidad y dirección",
  "Speed Curve Presets": "Curvas de velocidad",
  "Speed Curves": "Curvas de velocidad",
  "Spill Suppression": "Supresión de derrame",
  "Split (S)": "Partir (S)",
  "Split Screen": "Pantalla dividida",
  Stabilization: "Estabilización",
  Stabilize: "Estabilizar",
  Stage: "Escenario",
  Start: "Inicio",
  "Start Angle": "Ángulo inicial",
  "Start Fresh": "Empezar de cero",
  "Start Opacity": "Opacidad inicial",
  "Start Recording": "Empezar a grabar",
  "Start Time": "Inicio",
  "Start Tracking": "Empezar seguimiento",
  "Start a Motion Creator template": "Empezar con una plantilla de movimiento",
  "Start creating": "Empezar",
  "Start fresh with a new canvas": "Empezar con un lienzo nuevo",
  "Start with a pre-made project": "Empieza con un proyecto armado",
  "Start with pre-built project structures": "Empieza con una estructura ya armada",
  Status: "Estado",
  Stickers: "Pegatinas",
  "Stickers & Emojis": "Pegatinas y emojis",
  Stop: "Detener",
  "Stop Recording": "Detener grabación",
  "Stop recording": "Detener grabación",
  Strength: "Fuerza",
  Stroke: "Contorno",
  Style: "Estilo",
  Subtitle: "Subtítulo",
  "Subtitle Selected - Edit in Inspector": "Subtítulo seleccionado — edítalo en Propiedades",
  "Subtitle text": "Texto del subtítulo",
  "Switch angles during playback to create cuts": "Cambia de ángulo mientras reproduces para ir cortando",
  "Sync Audio": "Sincronizar audio",
  "Sync Mode": "Modo de sincronía",
  "Sync Settings": "Ajustes de sincronía",
  "Sync and switch between camera angles": "Sincroniza y cambia entre ángulos",
  "Sync and switch between multiple angles": "Sincroniza y cambia entre varios ángulos",
  "Sync clips to the beat of this audio": "Sincroniza los clips al beat de este audio",
  "System Audio": "Audio del sistema",
  "Tags (comma-separated)": "Etiquetas (separadas por coma)",
  "Target Language": "Idioma de destino",
  "Target size": "Tamaño objetivo",
  Temperature: "Temperatura",
  "Template Name": "Nombre de la plantilla",
  "Template Variables": "Variables de la plantilla",
  "Template saved successfully!": "Plantilla guardada",
  "Templates & Presets": "Plantillas y ajustes",
  "Testing...": "Probando…",
  "Text Align": "Alineación del texto",
  "Text Animation": "Animación de texto",
  "Text Behind Subject": "Texto detrás del sujeto",
  "Text Color": "Color del texto",
  "Text Content": "Contenido del texto",
  "Text Material": "Material de texto",
  "Text Properties": "Propiedades del texto",
  "Text animation previews": "Vistas previas de animación de texto",
  "Text appears behind people in the video": "El texto queda detrás de las personas",
  "Text material previews": "Vistas previas del material",
  "Text to Speech": "Texto a voz",
  "Text to Speech provider": "Proveedor de texto a voz",
  "Text to Speech/Voice To Speech/Sound Effects": "Texto a voz / voz a voz / efectos de sonido",
  "The live catalog includes focused tools for each desktop workspace.": "El catálogo trae herramientas específicas para cada espacio.",
  "This panel hit an error. Switch tabs and back to retry.": "Este panel falló. Cambia de pestaña y vuelve para reintentar.",
  "This template has no editable variables": "Esta plantilla no tiene variables editables",
  Threshold: "Umbral",
  "Tile Columns": "Columnas",
  Time: "Tiempo",
  Timeline: "Línea de tiempo",
  "Timeline zoom": "Zoom de la línea de tiempo",
  Timing: "Tiempos",
  "Timing Controls": "Control de tiempos",
  Tint: "Matiz",
  "Title and action safe margins": "Márgenes de seguridad",
  "Title safe": "Zona segura",
  "Toggle model list": "Ver la lista de modelos",
  Token: "Token",
  Tolerance: "Tolerancia",
  Tools: "Herramientas",
  "Total Silence": "Silencio total",
  "Track Layers": "Capas de pista",
  "Track Matte": "Máscara por pista",
  "Track layer types": "Tipos de capa",
  "Track layers": "Capas de pista",
  "Track name": "Nombre de la pista",
  "Track objects to attach elements": "Rastrea objetos para pegarles elementos",
  "Track objects to pin graphics, text, or effects": "Rastrea objetos para fijarles gráficos, texto o efectos",
  "Tracking Applied": "Seguimiento aplicado",
  "Tracking Complete": "Seguimiento terminado",
  "Tracking Failed": "Falló el seguimiento",
  "Tracking Region": "Región de seguimiento",
  "Tracking Speed": "Velocidad de seguimiento",
  "Tracking in Progress": "Siguiendo",
  "Transform Options": "Opciones de transformación",
  "Transform Style": "Estilo de transformación",
  Transition: "Transición",
  "Transition Type": "Tipo de transición",
  "Transition categories": "Categorías de transiciones",
  "Trigger Source (Voice Track)": "Pista que dispara (voz)",
  "Trim end to playhead (W)": "Recortar el final al cabezal (W)",
  "Trim start to playhead (Q)": "Recortar el inicio al cabezal (Q)",
  "Trusted Local": "Local de confianza",
  "Try Again": "Intentar de nuevo",
  "Try a different search or category.": "Prueba otra búsqueda u otra categoría.",
  "Try a different search term or category.": "Prueba otra búsqueda u otra categoría.",
  "Try adjusting filters": "Prueba con otros filtros",
  "Try adjusting your search or filter": "Prueba con otra búsqueda o filtro",
  Turbulence: "Turbulencia",
  Underline: "Subrayado",
  "Undo (⌘Z)": "Deshacer (⌘Z)",
  "Undo last AI turn": "Deshacer lo último de la IA",
  "Uniform Scale": "Escala uniforme",
  "Unknown shader": "Shader desconocido",
  "Unlock session to browse voices": "Desbloquea la sesión para ver las voces",
  Update: "Actualizar",
  "Upload Custom Font": "Subir tipografía",
  "Upload custom font": "Subir tipografía",
  "Uploading and submitting task...": "Subiendo y enviando…",
  "Use This Template": "Usar esta plantilla",
  "Use another clip as a track matte": "Usar otro clip como máscara",
  "Uses optical flow to generate smooth in-between frames": "Usa flujo óptico para generar cuadros intermedios",
  Value: "Valor",
  Vectorscope: "Vectorscopio",
  Vertical: "Vertical",
  "Video Dimensions": "Tamaño del video",
  "Video Effects": "Efectos de video",
  "Video Settings": "Ajustes de video",
  "Video file": "Archivo de video",
  "Video/image generation, upscaling, and creative AI tools": "Generación de video e imagen, escalado y herramientas creativas",
  Voice: "Voz",
  "Voice level that triggers ducking": "Nivel de voz que dispara la atenuación",
  "Volume Reduction": "Reducción de volumen",
  "Volume fader": "Control de volumen",
  Warmth: "Calidez",
  Warnings: "Avisos",
  "Wave Settings": "Ajustes de la onda",
  Waveform: "Forma de onda",
  Waves: "Ondas",
  "We found an unsaved project": "Encontramos un proyecto sin guardar",
  "Webcam Recording": "Grabación con cámara",
  "Webcam Resolution": "Resolución de la cámara",
  "Wet Level": "Nivel del efecto",
  "Wet/Dry": "Efecto/original",
  "White Balance": "Balance de blancos",
  Width: "Ancho",
  "Will encode H.264 without transparency.": "Se codifica en H.264, sin transparencia.",
  "X Offset": "Desplazamiento X",
  "X Position": "Posición X",
  "X Scale": "Escala X",
  "Y Offset": "Desplazamiento Y",
  "Y Position": "Posición Y",
  "Y Scale": "Escala Y",
  "You can keep editing once the export finishes.": "Puedes seguir editando cuando termine.",
  "Your name or username": "Tu nombre o usuario",
  "Zoom Scale": "Escala del zoom",
};

/**
 * Traduce si hay traducción; si no, devuelve el original.
 *
 * **Nunca devuelve vacío ni la clave decorada.** Un texto sin traducir sale en inglés y la pantalla
 * sigue siendo usable — que es la diferencia entre una traducción incremental y una a medias.
 */
export function traducir(original: string): string {
  return ES[original] ?? original;
}

/**
 * Bajo PRUEBAS, `t` devuelve el original — y no es pereza, es desacoplar.
 *
 * Las pruebas de este editor verifican COMPORTAMIENTO: que al pulsar un botón se parta un clip,
 * que un deslizador escriba su valor. El idioma de la etiqueta no es lo que prueban, pero sí es
 * lo que usan para ENCONTRAR el botón. Sin esto, cada frase que se traduce rompe pruebas que no
 * tienen nada que ver — y peor: obliga a reescribir aserciones en cada tanda de traducción, que
 * es justo cuando menos se quiere estar tocando las pruebas.
 *
 * Con la identidad bajo pruebas, traducir deja de poder romper la suite. Lo que sí se prueba es
 * el diccionario en sí, en `idioma.test.ts`, que llama a {@link traducir} directamente.
 *
 * (Ojo: esto NO afecta a producción. `import.meta.env.MODE` vale "test" solo bajo vitest.)
 */
const EN_PRUEBAS =
  typeof import.meta !== "undefined" && import.meta.env?.MODE === "test";

export function t(original: string): string {
  return EN_PRUEBAS ? original : traducir(original);
}

/** Cuántas frases hay traducidas. La usa la prueba que vigila que el diccionario no encoja. */
export function cuantasTraducidas(): number {
  return Object.keys(ES).length;
}
